sonar.projectKey=k8s-cicd-demo-site
sonar.projectName=Kubernetes CI/CD Demo Site
sonar.projectVersion=1.0
sonar.sources=src,scripts
sonar.exclusions=node_modules/**,k8s/**,argocd/**,docs/**
sonar.sourceEncoding=UTF-8
